export const DISCLAIMERS = {
  full: `TARMAC Pilot IQ is an independent educational assessment tool created for entertainment and study benchmarking purposes only. It is not affiliated with, endorsed by, or approved by the Federal Aviation Administration (FAA), any aviation authority, or any official pilot certification body. Your Pilot IQ score does not reflect your actual aeronautical knowledge, airmanship, flight proficiency, or fitness to fly. It is not a substitute for FAA-approved training, ground school, or examinations. This assessment should not be used to make any decisions about flight operations. Always consult a certified flight instructor (CFI) and official FAA materials for training guidance. Results are generated by AI and may contain errors.`,

  short: `For entertainment & study benchmarking only. Not affiliated with the FAA. Not a measure of actual flight proficiency.`,

  gate: `I understand that the Pilot IQ score is for entertainment and educational benchmarking only. It is not affiliated with the FAA, does not certify any aeronautical knowledge, and cannot be used to make decisions about flight operations.`,
} as const
