'use client'

import { useRef, useState } from 'react'
import { Maximize2, X, RotateCcw } from 'lucide-react'

interface Props {
  svg: string
  accessibilityDescription?: string
}

function touchDistance(touches: React.TouchList): number {
  const [a, b] = [touches[0], touches[1]]
  return Math.hypot(b.clientX - a.clientX, b.clientY - a.clientY)
}

/** Inline viewer for figures generated by Tarmac's own figure pipeline (src/lib/figures)
 *  — deterministic SVG today, possibly Gemini-generated raster assets later (see
 *  generators.ts). Mirrors SupplementViewer's zoom/pan/pinch interaction so a Tarmac
 *  Training Figure feels identical to a real FAA-supplement figure, just visually
 *  labeled as Tarmac's own synthetic training material rather than an official chart
 *  (see the Terms' figure-provenance rule — never implied to be an official FAA figure). */
export default function GeneratedFigureViewer({ svg, accessibilityDescription }: Props) {
  const [lightbox, setLightbox] = useState(false)
  const [scale, setScale] = useState(1)
  const [offset, setOffset] = useState({ x: 0, y: 0 })
  const dragRef = useRef<{ x: number; y: number; offsetX: number; offsetY: number } | null>(null)
  const pinchRef = useRef<{ distance: number; scale: number } | null>(null)

  function resetZoom() {
    setScale(1)
    setOffset({ x: 0, y: 0 })
  }

  function openLightbox() {
    resetZoom()
    setLightbox(true)
  }

  function closeLightbox() {
    setLightbox(false)
    resetZoom()
  }

  function zoomBy(factor: number) {
    setScale(prev => {
      const next = Math.min(4, Math.max(1, prev * factor))
      if (next === 1) setOffset({ x: 0, y: 0 })
      return next
    })
  }

  function handleWheel(e: React.WheelEvent) {
    e.preventDefault()
    zoomBy(e.deltaY < 0 ? 1.15 : 1 / 1.15)
  }

  function handleDoubleClick() {
    if (scale > 1) resetZoom()
    else setScale(2)
  }

  function handleMouseDown(e: React.MouseEvent) {
    if (scale <= 1) return
    dragRef.current = { x: e.clientX, y: e.clientY, offsetX: offset.x, offsetY: offset.y }
  }

  function handleMouseMove(e: React.MouseEvent) {
    if (!dragRef.current) return
    const dx = e.clientX - dragRef.current.x
    const dy = e.clientY - dragRef.current.y
    setOffset({ x: dragRef.current.offsetX + dx, y: dragRef.current.offsetY + dy })
  }

  function handleMouseUp() {
    dragRef.current = null
  }

  function handleTouchStart(e: React.TouchEvent) {
    if (e.touches.length === 2) {
      pinchRef.current = { distance: touchDistance(e.touches), scale }
    } else if (e.touches.length === 1 && scale > 1) {
      dragRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY, offsetX: offset.x, offsetY: offset.y }
    }
  }

  function handleTouchMove(e: React.TouchEvent) {
    if (e.touches.length === 2 && pinchRef.current) {
      e.preventDefault()
      const ratio = touchDistance(e.touches) / pinchRef.current.distance
      setScale(Math.min(4, Math.max(1, pinchRef.current.scale * ratio)))
    } else if (e.touches.length === 1 && dragRef.current) {
      const dx = e.touches[0].clientX - dragRef.current.x
      const dy = e.touches[0].clientY - dragRef.current.y
      setOffset({ x: dragRef.current.offsetX + dx, y: dragRef.current.offsetY + dy })
    }
  }

  function handleTouchEnd(e: React.TouchEvent) {
    if (e.touches.length < 2) pinchRef.current = null
    if (e.touches.length < 1) dragRef.current = null
  }

  return (
    <>
      <div className="rounded-xl overflow-hidden" style={{ border: '1px solid rgba(255,182,39,0.3)', background: 'rgba(255,182,39,0.05)' }}>
        <div className="flex items-center justify-between px-4 py-2.5" style={{ background: 'rgba(255,182,39,0.1)' }}>
          <span className="text-xs font-semibold text-[#FFB627] uppercase tracking-wide">Tarmac Training Figure</span>
        </div>
        <div className="p-3">
          <div
            className="relative group rounded-lg overflow-hidden cursor-pointer"
            style={{ background: '#0A1B3D' }}
            onClick={openLightbox}
            role="img"
            aria-label={accessibilityDescription || 'Tarmac training figure'}
            dangerouslySetInnerHTML={{ __html: svg }}
          />
          <p className="text-xs text-white/30 mt-2 text-center flex items-center justify-center gap-1.5">
            <Maximize2 className="w-3 h-3" /> Tap figure to enlarge
          </p>
        </div>
      </div>

      {lightbox && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-hidden touch-none"
          style={{ background: 'rgba(0,0,0,0.92)' }}
          onClick={closeLightbox}
          onWheel={handleWheel}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onMouseLeave={handleMouseUp}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
        >
          <button className="absolute top-4 right-4 text-white/70 hover:text-white transition-colors z-10" onClick={closeLightbox}>
            <X className="w-7 h-7" />
          </button>

          {scale > 1 && (
            <button
              className="absolute top-4 left-4 flex items-center gap-1.5 text-white/70 hover:text-white transition-colors z-10 text-sm bg-black/40 px-3 py-1.5 rounded-lg"
              onClick={e => { e.stopPropagation(); resetZoom() }}
            >
              <RotateCcw className="w-4 h-4" /> Reset ({Math.round(scale * 100)}%)
            </button>
          )}

          <div
            className="max-w-full max-h-full select-none"
            style={{
              width: 'min(90vw, 600px)',
              boxShadow: '0 0 60px rgba(0,0,0,0.8)',
              transform: `translate(${offset.x}px, ${offset.y}px) scale(${scale})`,
              cursor: scale > 1 ? 'grab' : 'zoom-in',
              transition: dragRef.current || pinchRef.current ? 'none' : 'transform 0.15s ease-out',
              borderRadius: '12px',
              overflow: 'hidden',
            }}
            role="img"
            aria-label={accessibilityDescription || 'Tarmac training figure'}
            onClick={e => e.stopPropagation()}
            onDoubleClick={e => { e.stopPropagation(); handleDoubleClick() }}
            onMouseDown={handleMouseDown}
            onTouchStart={handleTouchStart}
            dangerouslySetInnerHTML={{ __html: svg }}
          />
          <p className="absolute bottom-4 text-white/40 text-sm">Tarmac Training Figure · scroll or pinch to zoom, drag to pan</p>
        </div>
      )}
    </>
  )
}
